language: julia
os:
    - linux
    - osx
julia:
    - 0.3
    - nightly
notifications:
    email: false
sudo: false
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia -e 'Pkg.clone(pwd())'
    - julia -e 'Pkg.test("URITemplate", coverage=true)'
after_success:
    - julia -e 'cd(Pkg.dir("URITemplate")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
